server:
  port: 8080
  tomcat:
    threads:
      min-spare: 10
      max: 200
      
spring:
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sns?serverTimezone=Asia/Seoul
    username: yjhn0715
    password: 1234